services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: playto_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
